# Generated by Django 4.2.4 on 2023-09-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
