# Generated by Django 4.2.4 on 2023-09-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_remove_carrinho_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='itens',
            field=models.ManyToManyField(to='carrinho.itens'),
        ),
    ]
